### ISSUE TITLE
Paramétrer un temps de réponse pour chaque endpoint

### ISSUE THREAD

**Issue by cbarillet** [jntakpe/fra#11]
L'idée serait de rajouter un paramètre sur chaque endpoint permettant d'indiquer en combien de temps le testeur désire que le serveur réponde. Cela permet de tester des débit de connexion plus ou moins lent.

**Comment by jntakpe** [comment]
Corrigé et deployé aujourdhui

**Comment by cbarillet** [comment]
Testé et ne semble pas fonctionner.
J'ai mis 1200 sur le endpoint /rest/ios/bss/livret/syntheselivret et le endpoint répond toujours aussi vite.
Est-il possible que le serveur fasse une mise en cache et que de ce fait la requête ne passe plus par le code ?

**Comment by jntakpe** [comment]
En tout cas je n'arrive pas à reproduire. J'ai testé plusieurs fois la même requête elle met bien le temps paramétré pour répondre.
